# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATA_ROOT: ${DATA_ROOT:-/data}
      CUOPT_SOLVER_TIMEOUT_SEC: ${CUOPT_SOLVER_TIMEOUT_SEC:-120}
      CUOPT_URL: ${CUOPT_URL:-}         # leave empty to use local (in-process) solver
    volumes:
      - ./:/app
      - ${DATA_ROOT:-/data}:/data       # WRITEABLE!
    gpus: all
    restart: unless-stopped
    # no ports: backend is reachable as http://backend:8000 from UI container

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://backend:8000}
    ports:
      - "127.0.0.1::8501"               # random free host port -> container 8501
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./:/app
    restart: unless-stopped