# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      PYTHONPATH: /app
      PRIVATE_DATA_DIR: /data            # <— critical
      DATA_ROOT: ${DATA_ROOT:-/data}
      CUOPT_SOLVER_TIMEOUT_SEC: ${CUOPT_SOLVER_TIMEOUT_SEC:-120}
    # command: python -m uvicorn backend.main_miles:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
      - ${DATA_ROOT:-/data}:/data
    gpus: all
    restart: unless-stopped
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://backend:8000}
    command: streamlit run ui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    ports:
      - "127.0.0.1::8501"               # random free host port -> container 8501
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./:/app
    restart: unless-stopped