services:
  cuopt:
    image: ${CUOPT_IMAGE}
    container_name: cuopt
    gpus: all
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - "5000:5000"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: api
    environment:
      PYTHONPATH: /app:/app/src
      DATA_ROOT: ${DATA_ROOT}
      PRIVATE_DATA_DIR: ${PRIVATE_DATA_DIR}
      PRIORITY_MAP_FILE: /data/priority_map.json
      CUOPT_URL: http://cuopt:5000/v2
      CUOPT_SOLVER_TIMEOUT_SEC: ${CUOPT_SOLVER_TIMEOUT_SEC}
      CORS_ALLOW_ORIGINS: http://localhost:8501,http://ui:8501
    volumes:
      - ./:/app
      - ${DATA_ROOT}:/data
      - ${PRIVATE_DATA_DIR}:/data
    command: ["uvicorn","backend.main_miles:app","--host","0.0.0.0","--port","8000","--reload"]
    ports:
      - "8000:8000"
    depends_on:
      - cuopt
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: ui
    environment:
      API_BASE_URL: http://api:8000
      STREAMLIT_SERVER_RUN_ON_SAVE: "true"
    command: ["streamlit","run","ui/streamlit_app.py","--server.address=0.0.0.0","--server.port","8501"]
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./:/app
    restart: unless-stopped
