services:
  cuopt:
    ports:
      - "5000:5000"

  api:
    depends_on:
      cuopt:
        condition: service_started
    command: ["uvicorn","backend.main_miles:app","--host","0.0.0.0","--port","8000"]
    environment:
      ENFORCE_SAME_ISLAND: "true"
      USE_HAVERSINE_DEADHEAD: "true"
      HAV_MAX_DEADHEAD_ONE_WAY_MI: "120"
      CUOPT_URL: "http://cuopt:5000"
      CUOPT_SOLVE_PATH: "/cuopt/request"
      PRIVATE_DATA_DIR: "/data/private"
      CORS_ALLOW_ORIGINS: "http://localhost:8501"
    volumes:
      - ./backend:/app/backend:ro
      - ./src:/app/src:ro
      - ./data/private:/data/private   # writable
    ports:
      - "8000:8000"

    # Optional: requires recent Docker Compose (v2.22+). Remove if unsupported.
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./backend/requirements.txt

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    depends_on:
      api:
        condition: service_started
    environment:
      - API_BASE_URL=http://api:8000
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app/ui:ro
